### ISSUE TITLE
Macro parameter binding

### ISSUE THREAD

**Issue by skttl** [umbraco-community/Our-Umbraco-TagHelpers#1]
In stead of `our-macro-parameterKeyAlias` I would suggest something like

`<our-macro alias="myMacro" bind:start-node-id="43"/>` or `<our-macro alias="myMacro" bind:startNodeId="43"/>`

So the prefix is `bind:` (like in vue/alpine etc.), and then the keyalias can be kebab-cased, and then converted on the server to camelCase.

**Comment by warrenbuckley** [comment]
@skttl fixed and works with `bind:startNodeId`
