### ISSUE TITLE
Small Error on 'Our'

### ISSUE THREAD

**Issue by mikeleitzel** [umbraco-community/Our-Umbraco-TagHelpers#28]
SUPER SMALL ISSUE.

The installation instructions on 'our' are missing the 's'

dotnet add package Our.Umbraco.TagHelper  <-- missing s 
dotnet add package Our.Umbraco.TagHelper**s**

It is correct in the Installing description / section, but not correct in the quick-hitter above your name, Warren.

**Comment by warrenbuckley** [comment]
Thanks @mikeleitzel 
All fixed now :)
