### ISSUE TITLE
Async issues with UmbracoTagHelperCacheKeys

### ISSUE THREAD

**Issue by drpeck** [umbraco-community/Our-Umbraco-TagHelpers#52]
I get the error `InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.`.
The cause appears to be that `CacheTagHelper.ProcessAsync` is running async, but it changes `IUmbracoTagHelperCacheKeys.CacheKeys` which is not thread safe. I assume a `<our-cache />` running on a different thread has has changed the collection.

The solution is ConcurrentDictionary<TKey,TValue>. At least for me. Submitting a PR...

Sorry to not supply steps to re-create this issue. The joys of async make that very hard.

**Comment by drpeck** [comment]
PR submitted: https://github.com/umbraco-community/Our-Umbraco-TagHelpers/pull/53

**Comment by warrenbuckley** [comment]
Closed as fixed in PR #53
